/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import DB.DBConnection;
import static Tampilan.Payment.conn;
import static Tampilan.Payment.sql;
import static Tampilan.Register.ps;
import static Tampilan.Register.rs;
import javax.swing.JOptionPane;
/**
 *
 * @author hp proBook
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        backgroundMenu3 = new Background.BackgroundMenu();
        btnWilder = new javax.swing.JButton();
        btnCerulean = new javax.swing.JButton();
        btnQueen = new javax.swing.JButton();
        btnRegen = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backgroundMenu21 = new Background.BackgroundMenu2();
        btnDespair = new javax.swing.JButton();
        btnTinman = new javax.swing.JButton();
        btnWoman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWilder.setText("BUY");
        btnWilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWilderActionPerformed(evt);
            }
        });

        btnCerulean.setText("BUY");
        btnCerulean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeruleanActionPerformed(evt);
            }
        });

        btnQueen.setText("BUY");
        btnQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueenActionPerformed(evt);
            }
        });

        btnRegen.setText("BUY");
        btnRegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegenActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundMenu3Layout = new javax.swing.GroupLayout(backgroundMenu3);
        backgroundMenu3.setLayout(backgroundMenu3Layout);
        backgroundMenu3Layout.setHorizontalGroup(
            backgroundMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundMenu3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(backgroundMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundMenu3Layout.createSequentialGroup()
                        .addComponent(btnWilder, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCerulean, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnQueen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        backgroundMenu3Layout.setVerticalGroup(
            backgroundMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundMenu3Layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addGroup(backgroundMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWilder)
                    .addComponent(btnCerulean)
                    .addComponent(btnQueen)
                    .addComponent(btnRegen))
                .addGap(66, 66, 66)
                .addComponent(btnLogout)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(backgroundMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(backgroundMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab1.addTab("Halaman 1", jPanel3);

        btnDespair.setText("BUY");
        btnDespair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespairActionPerformed(evt);
            }
        });

        btnTinman.setText("BUY");
        btnTinman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinmanActionPerformed(evt);
            }
        });

        btnWoman.setText("BUY");
        btnWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWomanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundMenu21Layout = new javax.swing.GroupLayout(backgroundMenu21);
        backgroundMenu21.setLayout(backgroundMenu21Layout);
        backgroundMenu21Layout.setHorizontalGroup(
            backgroundMenu21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundMenu21Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnDespair, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnTinman, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        backgroundMenu21Layout.setVerticalGroup(
            backgroundMenu21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundMenu21Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addGroup(backgroundMenu21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinman)
                    .addComponent(btnDespair)
                    .addComponent(btnWoman))
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMenu21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMenu21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tab1.addTab("Halaman 2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab1.getAccessibleContext().setAccessibleName("1\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWilderActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWilderActionPerformed

    private void btnCeruleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeruleanActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCeruleanActionPerformed

    private void btnQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueenActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQueenActionPerformed

    private void btnRegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegenActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegenActionPerformed

    private void btnDespairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespairActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDespairActionPerformed

    private void btnTinmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinmanActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTinmanActionPerformed

    private void btnWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWomanActionPerformed
        Payment bayar = new Payment();
        bayar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWomanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Background.BackgroundMenu2 backgroundMenu21;
    private Background.BackgroundMenu backgroundMenu3;
    private javax.swing.JButton btnCerulean;
    private javax.swing.JButton btnDespair;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnQueen;
    private javax.swing.JButton btnRegen;
    private javax.swing.JButton btnTinman;
    private javax.swing.JButton btnWilder;
    private javax.swing.JButton btnWoman;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane tab1;
    // End of variables declaration//GEN-END:variables
}

