/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import javax.swing.JOptionPane;
import DB.DBConnection;
import static Tampilan.Payment.conn;
import static Tampilan.Register.conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
/**
 *
 * @author hp proBook
 */
public class Payment extends javax.swing.JFrame {
    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    ResultSet rs;
   
    
    public Payment() {
        conn = new DBConnection().setConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpayment1 = new Background.Backgroundpayment();
        backgroundpayment2 = new Background.Backgroundpayment();
        backgroundpayment3 = new Background.Backgroundpayment();
        backgroundpayment4 = new Background.Backgroundpayment();
        backgroundpayment5 = new Background.Backgroundpayment();
        backgroundpayment6 = new Background.Backgroundpayment();
        jPanel1 = new javax.swing.JPanel();
        backgroundlogin1 = new Background.Backgroundlogin();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idpembeli = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        ComboBook = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfBook1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-book-filled-20.png"))); // NOI18N
        jLabel8.setText("Book");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-book-filled-20.png"))); // NOI18N
        jLabel2.setText("Book_ID");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-plus-math-20.png"))); // NOI18N
        jLabel4.setText("Total item");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-barcode-20.png"))); // NOI18N
        jLabel6.setText("Price");

        btnCheck.setBackground(new java.awt.Color(182, 153, 173));
        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCheck.setText("CHECK");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnBeli.setBackground(new java.awt.Color(182, 153, 173));
        btnBeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBeli.setText("BUY");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        ComboBook.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ComboBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Books", "Wilder Girls", "The Cerulean", "The Queen of Nothing", "Regeneration", "Despair", "Tin Man", "The Woman Glass" }));
        ComboBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBookActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-barcode-20.png"))); // NOI18N
        jLabel7.setText("Total Payment");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-registration-32.png"))); // NOI18N
        jLabel3.setText("ID User");

        javax.swing.GroupLayout backgroundlogin1Layout = new javax.swing.GroupLayout(backgroundlogin1);
        backgroundlogin1.setLayout(backgroundlogin1Layout);
        backgroundlogin1Layout.setHorizontalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundlogin1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfBook1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBook, javax.swing.GroupLayout.Alignment.TRAILING, 0, 264, Short.MAX_VALUE)
                    .addComponent(idpembeli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTotal))
                .addContainerGap())
            .addGroup(backgroundlogin1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnBeli)
                .addGap(110, 110, 110))
        );
        backgroundlogin1Layout.setVerticalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundlogin1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboBook, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(btnBeli))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBookActionPerformed
        int harga = 0;
        int idbuku;
        
        if (ComboBook.getSelectedItem() == "Wilder Girls" ){
            idbuku = 001;
            harga = 65000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "The Cerulean" ){
            idbuku = 002;
            harga = 75000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "The Queen of Nothing" ){
            idbuku = 003;
            harga = 100000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "Regeneration" ){
            idbuku = 004;
            harga = 96500;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "Despair" ){
            idbuku = 005;
            harga = 82000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "Tin Man" ){
            idbuku = 006;
            harga = 97000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
        else if (ComboBook.getSelectedItem() == "The Woman Glass" ){
            idbuku = 007;
            harga = 102000;
            tfBook1.setText(String.valueOf(idbuku));
            tfPrice.setText(String.valueOf(harga));
        }
    }//GEN-LAST:event_ComboBookActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
       
        uang();
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        int IDUser = Integer.parseInt(idpembeli.getText());
        String BookName = ComboBook.getSelectedItem().toString();
       int BookID = Integer.parseInt(tfBook1.getText());
        int TotalItem = Integer.parseInt(tfJumlah.getText());
        String Price = tfPrice.getText();
        String TotalPayment = tfTotal.getText();
        
         try{
            sql = "INSERT INTO payment VALUES (?, ?, ?, ?, ?,?)";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, IDUser);
            ps.setInt(2, BookID);
            ps.setString(3, BookName);
            ps.setInt(4, TotalItem);
            ps.setString(5, Price);
            ps.setString(6, TotalPayment);
            
            
            int rt = ps.executeUpdate();    
            JOptionPane.showMessageDialog(null, "Selamat! Buku berhasil dibeli!",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
            System.out.println("Error" + e.getMessage());
        }
        Menu buku = new Menu();
        buku.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBook;
    private Background.Backgroundlogin backgroundlogin1;
    private Background.Backgroundpayment backgroundpayment1;
    private Background.Backgroundpayment backgroundpayment2;
    private Background.Backgroundpayment backgroundpayment3;
    private Background.Backgroundpayment backgroundpayment4;
    private Background.Backgroundpayment backgroundpayment5;
    private Background.Backgroundpayment backgroundpayment6;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnCheck;
    private javax.swing.JTextField idpembeli;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfBook1;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
public void uang() {
        try {
            int totals =0;
        int harga = Integer.parseInt(tfPrice.getText());
        int jumlah = Integer.parseInt(tfJumlah.getText());
       
        totals = harga * jumlah;
            DecimalFormat df = (DecimalFormat) DecimalFormat.getCurrencyInstance();
            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setCurrencySymbol("");
            dfs.setMonetaryDecimalSeparator(',');
            dfs.setGroupingSeparator('.');
            df.setDecimalFormatSymbols(dfs);
            String hsl = "Rp." + df.format(totals);
            String hasil = "Rp." + df.format(harga);
            tfTotal.setText(hsl);
            tfPrice.setText(hasil);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pengisian harga tidak boleh kosong");
        }
    }
}
